### ISSUE TITLE
Should Payment Providers keep their fees in the database? 

### ISSUE THREAD

**Issue by marcogbarcellos** [opencollective/ledger#1]
In the first migration version, I added the fields `fixedFee` and `percentageFee` for payment providers(stripe, paypal, etc) in [this file](https://github.com/opencollective/ledger/blob/master/database/migrations/201807310658_add_paymentProviders.js#L11-L13) more as a suggestion so I'd love to hear if anyone has any thoughts about storing these fees within the database instead of through the code.

**Comment by xdamman** [comment]
Given that we always have to have some code for each payment provider and that their numbers will be very small (< 5 for this year, < 20 for the foreseeable future), I don’t think that we need a table for that. Just having a directory in the paymentProviders directory seems enough to me with a manifest json to define some of those values and the features that they support (eg. one time payments, recurring payments, etc.)

**Comment by marcogbarcellos** [comment]
I see, makes sense.
