### ISSUE TITLE
Transaction types(Debit and Credit) and Negative amount

### ISSUE THREAD

**Issue by marcogbarcellos** [opencollective/ledger#2]
I was wondering if having Transactions `Types` and  Negative `amounts` might be redundant as if it's a debit it's negative. Did you guys have a specific reason to do the in the current api model or I'm missing something here? If not, What do you think about using one or another?

**Comment by znarf** [comment]
@marcogbarcellos I find the current elegant. I would keep it like that.

**Comment by marcogbarcellos** [comment]
We will keep as we have in the current production system: Types (Credit and Debit) and negative amounts. Mainly for simplicity's sake.
