### ISSUE TITLE
Renaming the Collective Model

### ISSUE THREAD

**Issue by marcogbarcellos** [opencollective/ledger#3]
When I started looking at the Open Collective API code, one of the things that got me for a while was the fact that the `Collective` Table could be of a type `Collective` but also an `User`(which in the end is also a Collective). It's completely right but the naming was just confusing me, perhaps my bad, for a while. 
I started looking at other double entry systems and some of the common terms are: Assets, Liabilities, Equities, Accounts, Journal.

Would it make sense to rename the Collective model into, for example(just a suggestion) `Account`. Then the types present in the Collective table today would be decoupled from there(some of them are already decoupled though), 

Collective Types as of today:
- BOT
- EVENT
- COLLECTIVE
- USER
- ORGANIZATION

**Comment by znarf** [comment]
@marcogbarcellos Working on the API, I'm facing the same problem and the best I could find so far is also "Account".

**Comment by marcogbarcellos** [comment]
Ok, For now I will try to use Account but as it's a prototype/mvp we can easily change the name again later on. thanks for the feedback

**Comment by marcogbarcellos** [comment]
We will use `Accounts`
